name=Boardoza DRV8317 Motor Driver
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza DRV8317 Motor Driver
paragraph=This library provides an easy-to-use API for interfacing with the DRV8317 motor driver. It supports configuration, control, and monitoring of DC and stepper motors. Designed for Arduino and PlatformIO projects, it includes example sketches and minimal dependencies.
category=Motor Control
url=https://github.com/Boardoza/Boardoza_DRV8317H_Three_Phase_BLDC_Driver_Breakout_Board
architectures=*